name: bank-carv
services:
  bank-account-db:
    container_name: bank-account-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD:
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - bank-account-db-data:/var/opt/mssql
    restart: always

networks:
  bank-network:
    name: bank-network

volumes:
  bank-account-db-data:
    name: bank-account-db-data

