--liquibase formatted sql
--changeset carolusquintus:0001

CREATE TABLE dbo.CUSTOMER (
    ID            VARBINARY(16) NOT NULL,
    NAME          VARCHAR(100)  NOT NULL,
    EMAIL         VARCHAR(100)  NOT NULL,
    MOBILE_NUMBER VARCHAR(20)   NOT NULL,
    CREATED_AT    DATETIME2     NOT NULL,
    UPDATED_AT    DATETIME2     DEFAULT NULL,
    CREATED_BY    VARCHAR(20)   NOT NULL,
    UPDATED_BY    VARCHAR(20)   DEFAULT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);
