--liquibase formatted sql
--changeset carolusquintus:0002

CREATE TABLE ACCOUNT (
    ID              VARBINARY(16)   NOT NULL,
    CUSTOMER_ID     VARBINARY(16)   NOT NULL,
    NUMBER          INT IDENTITY    NOT NULL,
    TYPE            VARCHAR(100)    NOT NULL,
    BRANCH_ADDRESS  VARCHAR(200)    NOT NULL,
    CREATED_AT      DATETIME2       NOT NULL,
    UPDATED_AT      DATETIME2       DEFAULT NULL,
    CREATED_BY      VARCHAR(20)     NOT NULL,
    UPDATED_BY      VARCHAR(20)     DEFAULT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID),
    CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);
