--liquibase formatted sql
--changeset carolusquintus:0003

ALTER TABLE dbo.ACCOUNT
DROP CONSTRAINT PK_ACCOUNT;

ALTER TABLE dbo.ACCOUNT
DROP COLUMN ID;

ALTER TABLE dbo.ACCOUNT
ADD CONSTRAINT PK_ACCOUNT_CUSTOMER PRIMARY KEY (CUSTOMER_ID);
