--liquibase formatted sql
--changeset carolusquintus:0003

ALTER TABLE dbo.CUSTOMER
ADD CONSTRAINT UQ_CUSTOMER_MOBILE_NUMBER UNIQUE (MOBILE_NUMBER);

--rollback ALTER TABLE dbo.CUSTOMER DROP CONSTRAINT UQ_CUSTOMER_MOBILE_NUMBER;
